baseURL = 'https://johnmakarov.github.io/victors-blog/'
languageCode = 'en-us'
title = ''
theme = 'my-blog-theme'

[markup]
  [markup.tableOfContents]
    startLevel = 2    # Начинать с H2
    endLevel = 4      # Заканчивать на H4
    ordered = false   # Маркированный список